---

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                      Prepare for SAP DB Load                               |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

- name:                                Get SAP Password from KeyVault
  hosts:                               localhost
  gather_facts:                        true
  vars_files:
    - vars/ansible-input-api.yaml      # API Input template with defaults

  tasks:

    - name:                            Include 0.1-passwords Role
      ansible.builtin.include_role:
        name:                          roles-misc/0.1-passwords
        public:                        true
      tags:
        - 0.1-passwords

    - name:                            Remove .step501 flag
      ansible.builtin.file:
        path:                          "{{ _workspace_directory }}/.step501"
        state:                          absent


# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                               SAP DB Load                                  |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

- name:                                DB Installation - HANA
  hosts:                               "{{ sap_sid|upper }}_PAS"

  remote_user:                         "{{ orchestration_ansible_user }}"
  become:                              true
  become_user:                         root
  gather_facts:                        true
  vars_files:
    - vars/ansible-input-api.yaml      # API Input template with defaults

  tasks:

    - name:                            Setting the dbload facts
      ansible.builtin.set_fact:
        tier:                          dbload                                                          # SAP Install phase: DBLOAD
        main_password:                 "{{ hostvars.localhost.sap_password }}"
      tags:
        - always

    - block:
        - name:                        Include 2.6-sap-mounts role
          ansible.builtin.include_role:
            name:                      roles-sap-os/2.6-sap-mounts
      tags:
        - 2.6-sap-mounts

    - block:
        - name:                        Include 5.1-dbload role
          ansible.builtin.include_role:
            name:                      roles-sap/5.1-dbload
      tags:
        - 5.1-dbload


# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                             HANA DB Logging                                |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

- name:                                Log results
  hosts:                               localhost
  gather_facts:                        true
  vars_files:
    - vars/ansible-input-api.yaml      # API Input template with defaults

  tasks:
    - name:                           Create .step501 flag
      ansible.builtin.file:
        path:                         "{{ _workspace_directory }}/.step501"
        state:                        touch
        mode:                         0755


...
# /*----------------------------------------------------------------------------8
# |                                   END                                       |
# +------------------------------------4---------------------------------------*/
