---

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                       Prepare for SAP APP Install                          |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

- name:                                Get SAP Password from KeyVault
  hosts:                               localhost
  gather_facts:                        true
  vars_files:
    - vars/ansible-input-api.yaml      # API Input template with defaults
  
  tasks:
    - name:                            Remove .step503 flag
      ansible.builtin.file:
        path:                          "{{ _workspace_directory }}/.step503"
        state:                         absent

    - name:                            Include 0.1 passwords role
      ansible.builtin.include_role:
        name:                          roles-misc/0.1-passwords
        public:                        true
      tags:
        - 0.1-passwords


# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                              SAP APP Install                               |
# |                                                                            |
# +------------------------------------4--------------------------------------*/


- name:                                SAP Installation - APP
  hosts:                               "{{ sap_sid|upper }}_APP"

  serial:                              1                                        # Cause App Servers to install sequentially
  remote_user:                         "{{ orchestration_ansible_user }}"
  become:                              true
  become_user:                         root
  gather_facts:                        true
  vars_files:
    - vars/ansible-input-api.yaml                                               # API Input template with defaults

  tasks:

    - name:                            Set 'app' tier facts
      ansible.builtin.set_fact:
        tier:                          app                                     # SAP Install phase: APP - Application Server
        main_password:                 "{{ hostvars.localhost.sap_password }}"

    - block:
        - name:                        Include 2.6-sap-mounts role
          ansible.builtin.include_role:
            name:                      roles-sap-os/2.6-sap-mounts
      tags:
        - 2.6-sap-mounts

    - block:
        - name:                        Include 5.3-app-install
          ansible.builtin.include_role:
            name:                      roles-sap/5.3-app-install
      tags:
        - 5.3-app-install


# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                              SAP APP Logging                               |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

- name:                                Log results
  hosts:                               localhost
  gather_facts:                        true
  vars_files:
    - vars/ansible-input-api.yaml      # API Input template with defaults

  tasks:
    - name:                            Create .step503 flag
      ansible.builtin.file:
        path:                          "{{ _workspace_directory }}/.step503"
        state:                         touch
        mode:                          0755


...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
