# /*----------------------------------------------------------------------------8
# |                                                                            |
# |                      Playbook for PACEMAKER config of HANA                  |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---

- hosts:                               "{{ sap_sid|upper }}_DB"

  name:                                PACEMAKER - HANA
  remote_user:                         "{{ orchestration_ansible_user }}"
  become:                              true
  become_user:                         root
  gather_facts:                        true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults

  tasks:

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                       Retrieving the SPN details                           |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

- hosts:                               localhost
  name:                                Get SPN from KeyVault
  remote_user:                         "{{ orchestration_ansible_user }}"
  become:                              false
  become_user:                         root
  gather_facts:                        true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults

# -------------------------------------+---------------------------------------8
#
# Build the list of tasks to be executed in order here.
#
# -------------------------------------+---------------------------------------8


  tasks:

    - name:                            Remove .step603 flag
      ansible.builtin.file:
        path:                          "{{ _workspace_directory }}/.step603"
        state:                         absent

    - name:                            Initialize tier
      ansible.builtin.set_fact:
        tier:                          fencing

    - name:                            Run the keyvault role
      include_role:
        name:                          roles-misc/0.2-kv-secrets
      tags:
        - kv-secrets

    - name:                            Run the password role
      include_role:
        name:                          roles-misc/0.1-passwords
        public:                        true
      tags:
        - 0.1-passwords


# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +------------------------------------4--------------------------------------*/

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                       Playbook for Pacemaker -HANA                         |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

- hosts:                               "{{ sap_sid|upper }}_DB"
  name:                                "PACEMAKER - HANA"
  remote_user:                         "{{ orchestration_ansible_user }}"
  become:                              true
  become_user:                         root
  gather_facts:                        true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults

  tasks:
# -------------------------------------+---------------------------------------8
#
# Build the list of tasks to be executed in order here.
#
# -------------------------------------+---------------------------------------8
    - name:                            Print the fencing tenant id
      debug:
        msg:                           "{{ hostvars.localhost.sap_fencing_spn_tenant_id }}"

    - name: Initialize facts
      set_fact:
        tier:                             ha
        password_ha_db_cluster:           "{{ hostvars.localhost.db_cluster_password }}"
        main_password:                    "{{ hostvars.localhost.sap_password }}"
        primary_instance_name:            "{{ ansible_play_hosts_all[0] }}"         # Setting up Primary Instance Name
        secondary_instance_name:          "{{ ansible_play_hosts_all[1] }}"         # Setting up Secondary Instance Name
        sap_hana_fencing_spn_client_id:   "{{ hostvars.localhost.sap_fencing_spn_client_id }}"
        sap_hana_fencing_spn_client_pwd:  "{{ hostvars.localhost.sap_fencing_spn_pwd }}"
        sap_hana_fencing_spn_tenant_id:   "{{ hostvars.localhost.sap_fencing_spn_tenant_id }}"
        when:                             db_high_availability
      tags:
        - always

    - block:
        - name:                           Run the hana sudoers role
          include_role:
            name:                         roles-os/1.11-accounts
            tasks_from:                   setup_hanausers_sudoers.yml
          when:                           db_high_availability
      tags:
        - 1.11-accounts
    - block:
        - name:                           Run the Pacemaker role
          include_role:
            name:                         roles-sap/5.5-hanadb-pacemaker
          when:                           db_high_availability
      tags:
        - 5.5-hanadb-pacemaker

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                       Logging the results                                  |
# |                                                                            |
# +------------------------------------4--------------------------------------*/


- hosts:                               localhost
  name:                                Log results
  remote_user:                         "{{ orchestration_ansible_user }}"
  become:                              false
  become_user:                         root
  gather_facts:                        true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults

  tasks:

    - name:                            Ensure the step file exists
      ansible.builtin.file:
        path:                          "{{ _workspace_directory }}/.step603"
        state:                         touch
        mode:                          0755


...


# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +------------------------------------4--------------------------------------*/
