# /*----------------------------------------------------------------------------8
# |                                                                             |
# | Playbook for PACEMAKER General Config                                       |
# | This playbook will setup a generic pacemaker cluster on DB and SCS hosts    |
# | The playbook user Azure fence Agent for node fencing. It gets the SPN       |
# | credentials from Key Vault. These credentials are used to create Stonith.  |
# +------------------------------------4---------------------------------------*|
---


- hosts:                               localhost
  name:                                Get Secrets from KeyVault
  gather_facts:                        true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults

  tasks:
    - name:                            Set 'ha' tier facts
      ansible.builtin.set_fact:
        tier:                          fencing

    - name:                            Remove .step6 flag
      ansible.builtin.file:
        path:                          "{{ _workspace_directory }}/.step6"
        state:                         absent

    - name:                            Include 0.1 passwords role
      ansible.builtin.include_role:
        name:                          roles-misc/0.1-passwords
        public:                        true
      tags:
        - 0.1-passwords

    - name:                            Include 0.2-kv-secrets role
      ansible.builtin.include_role:
        name:                          roles-misc/0.2-kv-secrets
        public:                        true
      tags:
        - 0.2-kv-secrets


- hosts:                               "{{ sap_sid|upper }}_DB"
  name:                                PACEMAKER - General Config - Database
  remote_user:                         "{{ orchestration_ansible_user }}"
  become:                              true
  become_user:                         root
  gather_facts:                        true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults


# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                 Playbook for Pacemaker Install                             |
# |                                                                            |
# +------------------------------------4--------------------------------------*/


# -------------------------------------+---------------------------------------8
#
# Build the list of tasks to be executed in order here.
#
# -------------------------------------+---------------------------------------8

# Specify the active tier for this playbook run

  tasks:

    - name:                            Set 'ha' tier facts
      ansible.builtin.set_fact:
        tier:                          ha
        main_password:                 "{{ hostvars.localhost.sap_password }}"
        password_ha_db_cluster:        "{{ hostvars.localhost.db_cluster_password }}"
      when: db_high_availability
      tags:
        - always

    - name:                              "Setting the pacemaker facts -DB"
      ansible.builtin.set_fact:
        primary_instance_name:           "{{ ansible_play_hosts_all[0] }}"         # Setting up Primary Instance Name
        secondary_instance_name:         "{{ ansible_play_hosts_all[1] }}"         # Setting up Secondary Instance Name
        sap_hana_fencing_spn_client_id:  "{{ hostvars.localhost.sap_fencing_spn_client_id }}"
        sap_hana_fencing_spn_client_pwd: "{{ hostvars.localhost.sap_fencing_spn_pwd }}"
        sap_hana_fencing_spn_tenant_id:  "{{ hostvars.localhost.sap_fencing_spn_tenant_id }}"
      when: db_high_availability

    - block:
        - name:                        Include 1.3-repository role
          ansible.builtin.include_role:
            name:                      roles-os/1.3-repository
          when:                        db_high_availability
      tags:
        - 1.3-repository

    - block:
        - name:                        Include 1.4-packages role
          ansible.builtin.include_role:
            name:                      roles-os/1.4-packages
          when:                        db_high_availability
      tags:
        - 1.4-packages

    - block:
      # Setup the kernel parameters required for pacemaker cluster VMs
        - name:                        Include 1.9-kernelparameters role
          ansible.builtin.include_role:
            name:                      roles-os/1.9-kernelparameters
          when:                        db_high_availability
      tags:
        - 1.9-kernelparameters

    - block:
        - name:                        Include 1.16-services role
          ansible.builtin.include_role:
            name:                      roles-os/1.16-services
          when:                        db_high_availability
      tags:
        - 1.16-services

    - block:
        - name:                        Include 1.11-accounts role
          ansible.builtin.include_role:
            name:                      roles-os/1.11-accounts
          when:                        db_high_availability
      tags:
        - 1.11-accounts

    - block:
        - name:                        Include 1.17-generic-pacemaker role
          ansible.builtin.include_role:
            name:                      roles-os/1.17-generic-pacemaker                         # Configures the Pacemaker cluster with Azure fence agent
          when:                        db_high_availability
      tags:
        - 1.17-generic-pacemaker

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                 Playbook for Pacemaker Install SCS                         |
# |                                                                            |
# +------------------------------------4--------------------------------------*/


- hosts:                               "{{ sap_sid|upper }}_SCS :
                                        {{ sap_sid|upper }}_ERS"

  name:                                PACEMAKER - General - Config - Central Services
  remote_user:                         "{{ orchestration_ansible_user }}"
  become:                              true
  become_user:                         root
  gather_facts:                        true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults

# -------------------------------------+---------------------------------------8
#
# Build the list of tasks to be executed in order here.
#
# -------------------------------------+---------------------------------------8

# Specify the active tier for this playbook run

  tasks:

    - name:                            Set 'ha' tier facts
      ansible.builtin.set_fact:
        tier:                          ha
        main_password:                 "{{ hostvars.localhost.sap_password }}"
        password_ha_db_cluster:        "{{ hostvars.localhost.db_cluster_password }}"
      when: scs_high_availability
      tags:
        - always

    - name:                              "Setting the pacemaker facts -DB"
      ansible.builtin.set_fact:
        primary_instance_name:           "{{ ansible_play_hosts_all[0] }}"         # Setting up Primary Instance Name
        secondary_instance_name:         "{{ ansible_play_hosts_all[1] }}"         # Setting up Secondary Instance Name
        sap_hana_fencing_spn_client_id:  "{{ hostvars.localhost.sap_fencing_spn_client_id }}"
        sap_hana_fencing_spn_client_pwd: "{{ hostvars.localhost.sap_fencing_spn_pwd }}"
        sap_hana_fencing_spn_tenant_id:  "{{ hostvars.localhost.sap_fencing_spn_tenant_id }}"
      when: scs_high_availability


# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                       Playbook for Generic Pacemaker Logging               |
# |                                                                            |
# +------------------------------------4--------------------------------------*/


- hosts:                               localhost
  name:                                Log results
  gather_facts:                        true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults

  tasks:
    - name:                            Create .step6 flag
      ansible.builtin.file:
        path:                          "{{ _workspace_directory }}/.step6"
        state:                         touch
        mode:                          0755


...
# /*---------------------------------------------------------------------------8
# |                                    END                                     |
# +------------------------------------4--------------------------------------*/
