---

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                        Prepare for SAP SCS Install                         |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

- name:                                Get SAP Password from KeyVault
  hosts:                               localhost
  gather_facts:                        true
  vars_files:
    - vars/ansible-input-api.yaml      # API Input template with defaults

  tasks:
    - name:                            Remove .step5 flag
      ansible.builtin.file:
        path:                          "{{ _workspace_directory }}/.step5"
        state:                         absent

    - name:                            Include 0.1 passwords role
      ansible.builtin.include_role:
        name:                          roles-misc/0.1-passwords
        public:                        true
      tags:
        - 0.1-passwords


# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                              SAP SCS Install                               |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

- name:                                SAP Installation - SCS
  hosts:                               "{{ sap_sid|upper }}_SCS"

  remote_user:                         "{{ orchestration_ansible_user }}"
  become:                              true
  become_user:                         root
  gather_facts:                        true
  vars_files:
    - vars/ansible-input-api.yaml                                               # API Input template with defaults

  tasks:

    - name:                            Set 'scs' tier facts
      ansible.builtin.set_fact:
        tier:                          scs
        main_password:                 "{{ hostvars.localhost.sap_password }}"
        scs_high_availability:         "{{ scs_high_availability }}"
      tags:
        - always

    - name:                            Show SAP password
      ansible.builtin.debug:
        msg:                           "{{ hostvars.localhost.sap_password }}"
        verbosity:                       2

    - block:
        - name:                        Include 5.0.0-scs-install role
          ansible.builtin.include_role:
            name:                      roles-sap/5.0.0-scs-install
      tags:
        - 5.0.0-scs-install


# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                              SAP SCS Logging                               |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

- name:                                Log results
  hosts:                               localhost
  gather_facts:                        true
  vars_files:
    - vars/ansible-input-api.yaml      # API Input template with defaults

  tasks:
    - name:                            Create .step5 flag
      ansible.builtin.file:
        path:                          "{{ _workspace_directory }}/.step5"
        state:                         touch
        mode:                          0755


...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
